[package]
name = "rust_os"
version = "0.1.0"
edition = "2018"

[dependencies]
bootloader = "0.9" #use the bootloader crate responsible for initializing the CPU and loading the kernel
volatile = "0.2.6" #so that the write should not be optimized right away and prevent it getting ommited 


# disabling unwinding(unwinding is the process of cleaning up {e.g., running destructors} before terminating or recovering from a panic)
[profile.dev] #profile used for `cargo build`
panic = "abort" #disable stack unwinding on panic

[profile.release] #profile used for `cargo build --release`
panic = "abort" #disable stack unwinding on panic
